name: benchmarks and validation
on:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      GAMMAPY_DATA: /home/runner/work/gammapy-benchmarks/gammapy-benchmarks/gammapy-datasets/dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: get env file
        run: curl -O https://raw.githubusercontent.com/gammapy/gammapy/main/environment-dev.yml
      - name: create and activate env
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: gammapy-dev
          environment-file: environment-dev.yml
          auto-update-conda: true
      - name: install gammapy
        run: |
          pip install git+https://github.com/gammapy/gammapy.git#egg=gammapy
          pip install psrecord
          conda info
          conda list
          gammapy info
      - name: download datasets
        # Including LST-1 Crab data from Zenodo
        run: |
          gammapy download datasets
          python utils/download_from_zenodo.py 11445184 $GAMMAPY_DATA/lst1_crab_data
      - name: run benchmarks
        run: |
          cd benchmarks
          python make.py run-benchmark all
          cd results
          python track_evolution.py
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        if: success()
        with:
          commit_author: GitHub Actions <actions@github.com>
          commit_message: commit results from benchmarks
#      - name: run validation
#        run: |
#          cd validation
#          python make.py run-validation all
      - name: slack notification
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Benchmarks and validations checks failed'
